### ISSUE TITLE
connection refused with shards

### ISSUE THREAD

**Issue by cop-discord** [nouman0103/winerp#15]
connection refused error 111
ufw already disabled nothing running on the specified port

**Comment by cop-discord** [comment]
So My bot is horizontally sharded meaning U have shard ids 0,1 in process 1, 2,3 in process 2, and so on, and it seems when doing bot.ipc.start the following is returned for the second process
```py
Traceback (most recent call last):
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/jishaku/features/python.py", line 189, in jsk_python2
    async for send, result in AsyncSender(executor):  # type: ignore
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/jishaku/functools.py", line 124, in _internal
    value = await base.asend(self.send_value)
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/jishaku/repl/compilation.py", line 154, in traverse
    async for send, result in AsyncSender(func_g(*self.args)):  # type: ignore
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/jishaku/functools.py", line 124, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
    await bot.ipc.start()
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/winerp/client.py", line 133, in start
    await self.__connect()
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/winerp/client.py", line 101, in __connect
    self.websocket = await websockets.connect(
  File "/root/.mamba/envs/rival/lib/python3.9/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by nouman0103** [comment]
Can you please share how you initialize client in the processes? Also, are your proccess and winerp-server hosted on the same server, or  connected through internet? Are you using localhost? Or ipv4 address or something?
